name: Frontend CI & CD

on:
  push:
    branches:
      - dev
      - main
      - feat/prod-cicd

jobs:
  build-and-deploy:
    name: Build Frontend & Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: .

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ott

      - name: Build React app (dev)
        if: github.ref_name == 'feat/prod-cicd'
        run: yarn build --mode development
        working-directory: ott

      - name: Build React app (prod)
        if: github.ref_name == 'main'
        run: yarn build
        working-directory: ott

      # === DEV 배포 ===
      - name: Set up SSH config for jump server
        if: github.ref_name == 'feat/prod-cicd'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.JUMP_SSH_KEY }}" > ~/.ssh/jump_key
          chmod 600 ~/.ssh/jump_key

          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/dev_key
          chmod 600 ~/.ssh/dev_key

          cat <<EOF > ~/.ssh/config
          Host fe-dev-server
              HostName ${{ secrets.SSH_HOST }}
              User ubuntu
              IdentityFile ~/.ssh/dev_key
              ProxyJump jump-server
              StrictHostKeyChecking no
              UserKnownHostsFile /dev/null

          Host jump-server
              HostName ${{ secrets.JUMP_SSH_HOST }}
              User ubuntu
              IdentityFile ~/.ssh/jump_key
              StrictHostKeyChecking no
              UserKnownHostsFile /dev/null
          EOF

      - name: Clean Nginx folder on remote
        if: github.ref_name == 'feat/prod-cicd'
        run: |
          ssh -F ~/.ssh/config fe-dev-server <<'EOF'
            set -eux
            sudo rm -rf /var/www/html/*
            sudo mkdir -p /var/www/html
          EOF

      - name: Copy built files to remote server
        if: github.ref_name == 'feat/prod-cicd'
        run: |
          scp -r -F ~/.ssh/config ott/dist/* fe-dev-server:/var/www/html/

      - name: Reload Nginx
        if: github.ref_name == 'feat/prod-cicd'
        run: |
          ssh -F ~/.ssh/config fe-dev-server <<'EOF'
            sudo systemctl reload nginx
          EOF

      # === PROD 배포 ===
      - name: Deploy to S3
        if: github.ref_name == 'main'
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.S3_ACCESS_KEY }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.S3_SECRET_KEY }}"
          export AWS_DEFAULT_REGION="ap-northeast-2"

          aws s3 sync ott/dist/ s3://onthe-top/frontend/prod/blue --delete

      - name: Invalidate CloudFront cache
        if: github.ref_name == 'main'
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.CLOUDFRONT_ACCESS_KEY }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.CLOUDFRONT_SECRET_KEY }}"
          export AWS_DEFAULT_REGION="ap-northeast-2"

          aws cloudfront create-invalidation \
            --distribution-id "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" \
            --paths "/*"
