name: Frontend Dev Deploy

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: .

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ott

      - name: Build React app (development)
        run: yarn build --mode development
        working-directory: ott

      - name: Set up SSH config
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.JUMP_SSH_KEY }}" > ~/.ssh/jump_key
          chmod 600 ~/.ssh/jump_key

          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/dev_key
          chmod 600 ~/.ssh/dev_key

          cat <<EOF > ~/.ssh/config
          Host fe-dev-server
              HostName ${{ secrets.SSH_HOST }}
              User ubuntu
              IdentityFile ~/.ssh/dev_key
              ProxyJump jump-server
              StrictHostKeyChecking no
              UserKnownHostsFile /dev/null

          Host jump-server
              HostName ${{ secrets.JUMP_SSH_HOST }}
              User ubuntu
              IdentityFile ~/.ssh/jump_key
              StrictHostKeyChecking no
              UserKnownHostsFile /dev/null
          EOF

      - name: Clean Nginx folder
        run: |
          ssh -F ~/.ssh/config fe-dev-server <<'EOF'
            sudo rm -rf /var/www/html/*
            sudo mkdir -p /var/www/html
          EOF

      - name: Copy built files to server
        run: |
          scp -r -F ~/.ssh/config ott/dist/* fe-dev-server:/var/www/html/

      - name: Reload Nginx
        run: |
          ssh -F ~/.ssh/config fe-dev-server <<'EOF'
            sudo systemctl reload nginx
          EOF
